# Generated by Django 4.1.3 on 2022-11-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0001_initial'),
        ('SIM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='modem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='modems.modem'),
        ),
    ]
