# Generated by Django 4.1.3 on 2022-11-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0002_alter_sim_modem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='modem',
        ),
    ]
