# Generated by Django 4.1.3 on 2022-11-26 13:35

import django.core.validators
from django.db import migrations, models
import system_for_remote_meter_points.SIM.models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0005_alter_sim_modem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='gsm_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), system_for_remote_meter_points.SIM.models.only_int]),
        ),
    ]
