# Generated by Django 4.1.3 on 2022-11-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0006_alter_sim_gsm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.TextField(choices=[('А1', 'А1'), ('Yettel', 'Yettel'), ('Vivacom', 'Vivacom')]),
        ),
    ]
