# Generated by Django 4.1.3 on 2022-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0006_alter_sim_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.TextField(choices=[('AONE', 'А1'), ('YETTEL', 'Yettel'), ('VIVACOM', 'Vivacom')]),
        ),
    ]
