# Generated by Django 4.1.3 on 2022-12-13 10:00

import django.core.validators
from django.db import migrations, models
import system_for_remote_meter_points.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0007_alter_sim_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='gsm_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), system_for_remote_meter_points.core.validators.only_int]),
        ),
        migrations.AlterField(
            model_name='sim',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
