# Generated by Django 4.1.3 on 2022-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0008_alter_sim_gsm_number_alter_sim_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.TextField(choices=[('А1', 'AONE'), ('Yettel', 'YETTEL'), ('Vivacom', 'VIVACOM')]),
        ),
    ]
