# Generated by Django 4.1.3 on 2022-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0013_alter_sim_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.TextField(choices=[('А1', 'А1'), ('Yettel', 'Yettel'), ('Vivacom', 'Vivacom')]),
        ),
    ]
