# Generated by Django 4.1.3 on 2022-11-28 22:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import system_for_remote_meter_points.modems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SIM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modem_number', models.CharField(max_length=6, unique=True, validators=[system_for_remote_meter_points.modems.models.only_int, django.core.validators.MinLengthValidator(6)])),
                ('sim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sim_key', to='SIM.sim', to_field='sim_number')),
            ],
        ),
    ]
