# Generated by Django 4.1.3 on 2022-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
