# Generated by Django 4.1.3 on 2022-11-23 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_points', '0001_initial'),
        ('modems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modem',
            name='meter_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='meter_points.meterpoint'),
        ),
    ]
