# Generated by Django 4.1.3 on 2022-11-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0002_modem_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modem',
            name='updated_date',
        ),
    ]
