# Generated by Django 4.1.3 on 2022-12-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0004_alter_sim_user'),
        ('modems', '0004_alter_modem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modem',
            name='sim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sim_key', to='SIM.sim', to_field='sim_number'),
        ),
    ]
