# Generated by Django 4.1.3 on 2022-11-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0005_alter_sim_modem'),
        ('modems', '0004_remove_modem_meter_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='sim',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='sim_key', to='SIM.sim'),
            preserve_default=False,
        ),
    ]
