# Generated by Django 4.1.3 on 2022-11-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meter_points', '0004_meterpoint_modem'),
        ('modems', '0005_modem_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='meter_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_point_modem_key', to='meter_points.meterpoint'),
        ),
    ]
