# Generated by Django 4.1.3 on 2022-11-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0005_alter_sim_modem'),
        ('modems', '0006_modem_meter_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modem',
            name='sim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sim_key', to='SIM.sim'),
        ),
    ]
