# Generated by Django 4.1.3 on 2022-11-27 22:17

import django.core.validators
from django.db import migrations, models
import system_for_remote_meter_points.modems.models


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0007_alter_modem_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modem',
            name='modem_number',
            field=models.CharField(max_length=6, unique=True, validators=[system_for_remote_meter_points.modems.models.only_int, django.core.validators.MinLengthValidator(6)]),
        ),
    ]
