# Generated by Django 4.1.3 on 2022-11-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_devices', '0002_meterdevice_updateddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdevice',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='meterdevice',
            name='updateddate',
            field=models.DateField(auto_now=True),
        ),
    ]
