# Generated by Django 4.1.3 on 2022-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_devices', '0002_meterdevice_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdevice',
            name='meter_device_read_cycle',
            field=models.TextField(choices=[('Read per 15 minute', 'Read per 15 minute'), ('Read per 1 hour', 'Read per 1 hour'), ('Read per 8 hours', 'Read per 8 hours'), ('Read per 24 hours', 'Read per 24 hours')], default=1),
            preserve_default=False,
        ),
    ]
