# Generated by Django 4.1.3 on 2022-11-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_devices', '0002_alter_meterdevice_meter_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdevice',
            name='meter_point',
        ),
    ]
