# Generated by Django 4.1.3 on 2022-11-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter_devices', '0003_remove_meterdevice_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdevice',
            name='updateddate',
        ),
    ]
