# Generated by Django 4.1.3 on 2022-11-27 22:56

import django.core.validators
from django.db import migrations, models
import system_for_remote_meter_points.meter_devices.models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_devices', '0006_meterdevice_meter_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdevice',
            name='meter_device_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16), system_for_remote_meter_points.meter_devices.models.only_int]),
        ),
    ]
