# Generated by Django 4.1.3 on 2022-12-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_devices', '0018_alter_meterdevice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdevice',
            name='meter_device_read_cycle',
            field=models.TextField(choices=[('Read per 15 minute', 'Read per 15 minute'), ('Read per 1 hour', 'Read per 1 hour'), ('Read per 8 hours', 'Read per 8 hours'), ('Read per 24 hours', 'Read per 24 hours')]),
        ),
        migrations.AlterField(
            model_name='meterdevice',
            name='meter_device_type',
            field=models.TextField(choices=[('ISKRA', 'ISKRA'), ('GAMA', 'GAMA'), ('AMT', 'AMT'), ('Microstar', 'Microstar')]),
        ),
    ]
