# Generated by Django 4.1.3 on 2022-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_appuser_kid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.ImageField(upload_to='user_photos/'),
        ),
    ]
