# Generated by Django 4.1.3 on 2022-12-06 17:05

import django.core.validators
from django.db import migrations, models
import system_for_remote_meter_points.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='department',
            field=models.TextField(choices=[('DOSO', 'DOSO'), ('OSP', 'OSP'), ('Auditor', 'Auditor'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4), system_for_remote_meter_points.accounts.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4), system_for_remote_meter_points.accounts.models.validate_only_letters]),
        ),
    ]
