# Generated by Django 4.1.3 on 2022-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_department_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='department',
            field=models.TextField(choices=[('DOSO', 'DOSO'), ('OSP', 'OSP'), ('AUDITOR', 'Auditor'), ('OTHER', 'Other')]),
        ),
    ]
