# Generated by Django 4.1.3 on 2022-11-28 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modems', '0001_initial'),
        ('meter_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('constant', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(80000)])),
                ('voltage', models.TextField(choices=[('Ниско', 'Ниско'), ('Средно', 'Средно'), ('Високо', 'Високо')])),
                ('regional_center', models.TextField(choices=[('Варна', 'Варна'), ('Добрич', 'Добрич'), ('Шумен', 'Шумен'), ('Търговище', 'Търговище'), ('Велико Търново', 'Велико Търново'), ('Русе', 'Русе'), ('Разград', 'Разград'), ('Силистра', 'Силистра'), ('Габрово', 'Габрово')])),
                ('operation', models.TextField(choices=[('Възсатновяване на комуникация', 'Възсатновяване на комуникация'), ('Добавяне на нова точка', 'Добавяне на нова точка'), ('Подмяна на електромер', 'Подмяна на електромер'), ('Подмяна на модем и/или СИМ карта', 'Подмяна на модем и/или СИМ карта'), ('Изтриване на точка', 'Изтриване на точка'), ('Смяна на константа', 'Смяна на константа'), ('Друго (в ,,Коментарите"")', 'Друго (в ,,Коментарите"")')])),
                ('result_operation', models.TextField(choices=[('Няма комуникация', 'Няма комуникация'), ('Има комуникация', 'Има комуникация'), ('В процес на изпълнение...', 'В процес на изпълнение...')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('meter_device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='meter_device_meter_point_key', to='meter_devices.meterdevice', to_field='meter_device_number')),
                ('modem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modem_meter_point_key', to='modems.modem', to_field='modem_number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
