# Generated by Django 4.1.3 on 2022-11-23 20:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('constant', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(80000)])),
                ('voltage', models.TextField(choices=[('Ниско', 'Ниско'), ('Средно', 'Средно'), ('Високо', 'Високо')])),
                ('regional_center', models.TextField(choices=[('Варна', 'Варна'), ('Добрич', 'Добрич'), ('Шумен', 'Шумен'), ('Търговище', 'Търговище'), ('Велико Търново', 'Велико Търново'), ('Русе', 'Русе'), ('Разград', 'Разград'), ('Силистра', 'Силистра'), ('Габрово', 'Габрово')])),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
