# Generated by Django 4.1.3 on 2022-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_points', '0002_remove_meterpoint_ip_address_meterpoint_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterpoint',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='operation',
            field=models.TextField(choices=[('Възсатновяване на комуникация', 'Възсатновяване на комуникация'), ('Добавяне на нова точка', 'Добавяне на нова точка'), ('Подмяна на електромер', 'Подмяна на електромер'), ('Подмяна на модем и/или СИМ карта', 'Подмяна на модем и/или СИМ карта'), ('Изтриване на точка', 'Изтриване на точка'), ('Смяна на константа', 'Смяна на константа'), ('Друго (в ,,Коментарите"")', 'Друго (в ,,Коментарите"")')]),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='result_operation',
            field=models.TextField(choices=[('Няма комуникация', 'Няма комуникация'), ('Има комуникация', 'Има комуникация'), ('В процес на изпълнение...', 'В процес на изпълнение...')]),
        ),
    ]
