# Generated by Django 4.1.3 on 2022-11-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0005_modem_sim'),
        ('meter_points', '0003_alter_meterpoint_comment_alter_meterpoint_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterpoint',
            name='modem',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modem_meter_point_key', to='modems.modem'),
            preserve_default=False,
        ),
    ]
