# Generated by Django 4.1.3 on 2022-11-29 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_points', '0005_alter_meterpoint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterpoint',
            name='constant',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(80000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
