# Generated by Django 4.1.3 on 2022-12-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0004_alter_modem_user'),
        ('meter_devices', '0005_alter_meterdevice_user'),
        ('meter_points', '0007_alter_meterpoint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterpoint',
            name='meter_device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter_device_meter_point_key', to='meter_devices.meterdevice', to_field='meter_device_number'),
        ),
        migrations.AlterField(
            model_name='meterpoint',
            name='modem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modem_meter_point_key', to='modems.modem', to_field='modem_number'),
        ),
    ]
