# Generated by Django 4.1.3 on 2022-11-28 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)])),
                ('constant', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(80000)])),
                ('voltage', models.TextField(choices=[('Ниско', 'Ниско'), ('Средно', 'Средно'), ('Високо', 'Високо')])),
                ('regional_center', models.TextField(choices=[('Варна', 'Варна'), ('Добрич', 'Добрич'), ('Шумен', 'Шумен'), ('Търговище', 'Търговище'), ('Велико Търново', 'Велико Търново'), ('Русе', 'Русе'), ('Разград', 'Разград'), ('Силистра', 'Силистра'), ('Габрово', 'Габрово')])),
                ('operation', models.TextField(choices=[('Възсатновяване на комуникация', 'Възсатновяване на комуникация'), ('Добавяне на нова точка', 'Добавяне на нова точка'), ('Подмяна на електромер', 'Подмяна на електромер'), ('Подмяна на модем и/или СИМ карта', 'Подмяна на модем и/или СИМ карта'), ('Изтриване на точка', 'Изтриване на точка'), ('Смяна на константа', 'Смяна на константа'), ('Друго (в ,,Коментарите"")', 'Друго (в ,,Коментарите"")')])),
                ('result_operation', models.TextField(choices=[('Няма комуникация', 'Няма комуникация'), ('Има комуникация', 'Има комуникация'), ('В процес на изпълнение...', 'В процес на изпълнение...')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('modem', models.CharField(max_length=255)),
                ('meter_device', models.CharField(max_length=255)),
            ],
        ),
    ]
