# Generated by Django 4.1.3 on 2022-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ip_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='sim_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
