# Generated by Django 4.1.3 on 2022-11-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_ip_address_task_sim_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sim_number',
        ),
    ]
