# Generated by Django 4.1.3 on 2022-11-29 20:06

import django.core.validators
from django.db import migrations, models
import system_for_remote_meter_points.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_ip_address_remove_task_sim_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='constant',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(80000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='meter_device',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16), system_for_remote_meter_points.tasks.models.only_int]),
        ),
        migrations.AlterField(
            model_name='task',
            name='modem',
            field=models.CharField(max_length=6, validators=[system_for_remote_meter_points.tasks.models.only_int, django.core.validators.MinLengthValidator(6)]),
        ),
    ]
