# Generated by Django 4.1.3 on 2022-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_mp_name_alter_task_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='operation',
            field=models.TextField(choices=[('', 'Operation'), ('Restore communication', 'Restore communication'), ('Add new meter points', 'Add new meter points'), ('Replace meter device', 'Replace meter device'), ('Replace modem and/or SIM card', 'Replace modem and/or SIM card'), ('Delete meter points', 'Delete meter points'), ('Add new constant', 'Add new constant'), ('Other (in ,,Comment")', 'Other (in ,,Comment")')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='regional_center',
            field=models.TextField(choices=[('', 'Regional center'), ('Varna', 'Varna'), ('Dobrich', 'Dobrich'), ('Shumen', 'Shumen'), ('Targovishte', 'Targovishte'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Ruse', 'Ruse'), ('Razgrad', 'Razgrad'), ('Silistra', 'Silistra'), ('Gabrovo', 'Gabrovo')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='result_operation',
            field=models.TextField(choices=[('', 'Result'), ('No communication', 'No communication'), ('Successful communication', 'Successful communication'), ('In progress...', 'In progress...')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='voltage',
            field=models.TextField(choices=[('', 'Voltage'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')]),
        ),
    ]
