# Generated by Django 4.1.3 on 2022-12-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_username_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
